all:
	cls ; python mweljsonrpc.py ../data/mwel01.xml
test:
	cls ; python mweljsonrpc.py ../data/mwel01.xml ../data/mwel03.xml ../data/mwel03.xml
data:
	cls ; more ../data/mwel01.xml ../data/mwel02.xml ../data/mwel03.xml
