all:	
	cls
	@echo '        Performance and Stress Test Suit - Version 1.0.'
	@echo ''
	@echo '|==> The Options are as follows so please use one:'
	@echo '     $ make syslog           - This is the performance test for syslog'
	@echo '     $ make snort            - This is the performance test for snort'
	@echo '     $ make sshd             - This is the performance test for sshd'
	@echo '     $ make tcpd             - This is the performance test for tcpd'
	@echo '     $ make cef              - This is the performance test for cef'
	@echo '     $ make ftpd             - This is the performance test for ftpd'
	@echo '     $ make vsftpd           - This is the performance test for vsftpd'
	@echo '     $ make ncsa             - This is the performance test for ncsa'
	@echo ''
	@echo '     $ make stress           - This is the stress test for 10,000 event'
	@echo ''

stress:
	cls
	@echo 'Stress Testing for 10000 Syslog Evenet'
	date
	python ../syslogjsonrpc/syslogjsonrpc.py -n 10000 syslog-10000.dat 
	date

sshd:
	@echo off
	cls
	@echo 'Performace Testing for 100 SSHD Evenet'
	date
	python ../sshdjsonrpc/sshdjsonrpc.py -n 100 sshd-100.dat
	date
	@echo ''
	@echo 'Performace Testing for 200 SSHD Evenet'
	date
	python ../sshdjsonrpc/sshdjsonrpc.py -n 200 sshd-200.dat
	date
	@echo ''
	@echo 'Performace Testing for 300 SSHD Evenet'
	date
	python ../sshdjsonrpc/sshdjsonrpc.py -n 300 sshd-300.dat
	date
	@echo ''
	@echo 'Performace Testing for 400 SSHD Evenet'
	date
	python ../sshdjsonrpc/sshdjsonrpc.py -n 400 sshd-400.dat
	date
	@echo ''
	@echo 'Performace Testing for 500 SSHD Evenet'
	date
	python ../sshdjsonrpc/sshdjsonrpc.py -n 500 sshd-500.dat
	date
	@echo ''
	@echo 'Performace Testing for 600 SSHD Evenet'
	date
	python ../sshdjsonrpc/sshdjsonrpc.py -n 600 sshd-600.dat
	date
	@echo ''
	@echo 'Performace Testing for 700 SSHD Evenet'
	date
	python ../sshdjsonrpc/sshdjsonrpc.py -n 700 sshd-700.dat
	date
	@echo ''
	@echo 'Performace Testing for 800 SSHD Evenet'
	date
	python ../sshdjsonrpc/sshdjsonrpc.py -n 800 sshd-800.dat
	date
	@echo ''
	@echo 'Performace Testing for 900 SSHD Evenet'
	date
	python ../sshdjsonrpc/sshdjsonrpc.py -n 900 sshd-900.dat
	date
	@echo ''
	@echo 'Performace Testing for 1000 SSHD Evenet'
	date
	python ../sshdjsonrpc/sshdjsonrpc.py -n 1000 sshd-1000.dat
	date

cef:
	@echo off
	cls
	@echo 'Performace Testing for 100 CEF Evenet'
	date
	python ../cefjsonrpc/cefjsonrpc.py -n 100 cef-100.dat
	date
	@echo ''
	@echo 'Performace Testing for 200 CEF Evenet'
	date
	python ../cefjsonrpc/cefjsonrpc.py -n 200 cef-200.dat
	date
	@echo ''
	@echo 'Performace Testing for 300 CEF Evenet'
	date
	python ../cefjsonrpc/cefjsonrpc.py -n 300 cef-300.dat
	date
	@echo ''
	@echo 'Performace Testing for 400 CEF Evenet'
	date
	python ../cefjsonrpc/cefjsonrpc.py -n 400 cef-400.dat
	date
	@echo ''
	@echo 'Performace Testing for 500 CEF Evenet'
	date
	python ../cefjsonrpc/cefjsonrpc.py -n 500 cef-500.dat
	date
	@echo ''
	@echo 'Performace Testing for 600 CEF Evenet'
	date
	python ../cefjsonrpc/cefjsonrpc.py -n 600 cef-600.dat
	date
	@echo ''
	@echo 'Performace Testing for 700 CEF Evenet'
	date
	python ../cefjsonrpc/cefjsonrpc.py -n 700 cef-700.dat
	date
	@echo ''
	@echo 'Performace Testing for 800 CEF Evenet'
	date
	python ../cefjsonrpc/cefjsonrpc.py -n 800 cef-800.dat
	date
	@echo ''
	@echo 'Performace Testing for 900 CEF Evenet'
	date
	python ../cefjsonrpc/cefjsonrpc.py -n 900 cef-900.dat
	date
	@echo ''
	@echo 'Performace Testing for 1000 CEF Evenet'
	date
	python ../cefjsonrpc/cefjsonrpc.py -n 1000 cef-1000.dat
	date

tcpd:
	@echo off
	cls
	@echo 'Performace Testing for 100 TCPD Evenet'
	date
	python ../tcpdjsonrpc/tcpdjsonrpc.py -n 100 tcpd-100.dat
	date
	@echo ''
	@echo 'Performace Testing for 200 TCPD Evenet'
	date
	python ../tcpdjsonrpc/tcpdjsonrpc.py -n 200 tcpd-200.dat
	date
	@echo ''
	@echo 'Performace Testing for 300 TCPD Evenet'
	date
	python ../tcpdjsonrpc/tcpdjsonrpc.py -n 300 tcpd-300.dat
	date
	@echo ''
	@echo 'Performace Testing for 400 TCPD Evenet'
	date
	python ../tcpdjsonrpc/tcpdjsonrpc.py -n 400 tcpd-400.dat
	date
	@echo ''
	@echo 'Performace Testing for 500 TCPD Evenet'
	date
	python ../tcpdjsonrpc/tcpdjsonrpc.py -n 500 tcpd-500.dat
	date
	@echo ''
	@echo 'Performace Testing for 600 TCPD Evenet'
	date
	python ../tcpdjsonrpc/tcpdjsonrpc.py -n 600 tcpd-600.dat
	date
	@echo ''
	@echo 'Performace Testing for 700 TCPD Evenet'
	date
	python ../tcpdjsonrpc/tcpdjsonrpc.py -n 700 tcpd-700.dat
	date
	@echo ''
	@echo 'Performace Testing for 800 TCPD Evenet'
	date
	python ../tcpdjsonrpc/tcpdjsonrpc.py -n 800 tcpd-800.dat
	date
	@echo ''
	@echo 'Performace Testing for 900 TCPD Evenet'
	date
	python ../tcpdjsonrpc/tcpdjsonrpc.py -n 900 tcpd-900.dat
	date
	@echo ''
	@echo 'Performace Testing for 1000 TCPD Evenet'
	date
	python ../tcpdjsonrpc/tcpdjsonrpc.py -n 1000 tcpd-1000.dat
	date

syslog:
	@echo off
	cls
	@echo 'Performace Testing for 100 Syslog Evenet'
	date
	python ../syslogjsonrpc/syslogjsonrpc.py -n 100 syslog-100.dat 
	date
	@echo ''
	@echo 'Performace Testing for 200 Syslog Evenet'
	date
	python ../syslogjsonrpc/syslogjsonrpc.py -n 200 syslog-200.dat
	date
	@echo ''
	@echo 'Performace Testing for 300 Syslog Evenet'
	date
	python ../syslogjsonrpc/syslogjsonrpc.py -n 300 syslog-300.dat
	date
	@echo ''
	@echo 'Performace Testing for 400 Syslog Evenet'
	date
	python ../syslogjsonrpc/syslogjsonrpc.py -n 400 syslog-400.dat
	date
	@echo ''
	@echo 'Performace Testing for 500 Syslog Evenet'
	date
	python ../syslogjsonrpc/syslogjsonrpc.py -n 500 syslog-500.dat
	date
	@echo ''
	@echo 'Performace Testing for 600 Syslog Evenet'
	date
	python ../syslogjsonrpc/syslogjsonrpc.py -n 600 syslog-600.dat
	date
	@echo '' 
	@echo 'Performace Testing for 700 Syslog Evenet'
	date
	python ../syslogjsonrpc/syslogjsonrpc.py -n 700 syslog-700.dat
	date
	@echo ''
	@echo 'Performace Testing for 800 Syslog Evenet'
	date
	python ../syslogjsonrpc/syslogjsonrpc.py -n 800 syslog-800.dat
	date
	@echo ''
	@echo 'Performace Testing for 900 Syslog Evenet'
	date
	python ../syslogjsonrpc/syslogjsonrpc.py -n 900 syslog-900.dat
	date
	@echo ''
	@echo 'Performace Testing for 1000 Syslog Evenet'
	date
	python ../syslogjsonrpc/syslogjsonrpc.py -n 1000 syslog-1000.dat
	date

snort:
	@echo off
	cls
	@echo 'Performace Testing for 100 Snort Evenet'
	date
	python ../snortjsonrpc/snortjsonrpc.py -n 100 snort-100.dat 
	date
	@echo ''
	@echo 'Performace Testing for 200 Snort Evenet'
	date
	python ../snortjsonrpc/snortjsonrpc.py -n 200 snort-200.dat
	date
	@echo ''
	@echo 'Performace Testing for 300 Snort Evenet'
	date
	python ../snortjsonrpc/snortjsonrpc.py -n 300 snort-300.dat
	date
	@echo ''
	@echo 'Performace Testing for 400 Snort Evenet'
	date
	python ../snortjsonrpc/snortjsonrpc.py -n 400 snort-400.dat
	date
	@echo ''
	@echo 'Performace Testing for 500 Snort Evenet'
	date
	python ../snortjsonrpc/snortjsonrpc.py -n 500 snort-500.dat
	date
	@echo ''
	@echo 'Performace Testing for 600 Snort Evenet'
	date
	python ../snortjsonrpc/snortjsonrpc.py -n 600 snort-600.dat
	date
	@echo '' 
	@echo 'Performace Testing for 700 Snort Evenet'
	date
	python ../snortjsonrpc/snortjsonrpc.py -n 700 snort-700.dat
	date
	@echo ''
	@echo 'Performace Testing for 800 Snort Evenet'
	date
	python ../snortjsonrpc/snortjsonrpc.py -n 800 snort-800.dat
	date
	@echo ''
	@echo 'Performace Testing for 800 Snort Evenet'
	date
	python ../snortjsonrpc/snortjsonrpc.py -n 800 snort-800.dat
	date
	@echo ''
	@echo 'Performace Testing for 900 Snort Evenet'
	date
	python ../snortjsonrpc/snortjsonrpc.py -n 900 snort-900.dat
	date
	@echo ''
	@echo 'Performace Testing for 1000 Syslog Evenet'
	date
	python ../snortjsonrpc/snortjsonrpc.py -n 1000 snort-1000.dat
	date

ftpd:
	@echo off
	cls
	@echo 'Performace Testing for 100 FTP Evenet'
	date
	python ../ftpdjsonrpc/ftpdjsonrpc.py -n 100 ftpd-100.dat
	date
	@echo ''
	@echo 'Performace Testing for 200 FTP Evenet'
	date
	python ../ftpdjsonrpc/ftpdjsonrpc.py -n 200 ftpd-200.dat
	date
	@echo ''
	@echo 'Performace Testing for 300 FTP Evenet'
	date
	python ../ftpdjsonrpc/ftpdjsonrpc.py -n 300 ftpd-300.dat
	date
	@echo ''
	@echo 'Performace Testing for 400 FTP Evenet'
	date
	python ../ftpdjsonrpc/ftpdjsonrpc.py -n 400 ftpd-400.dat
	date
	@echo ''
	@echo 'Performace Testing for 500 FTP Evenet'
	date
	python ../ftpdjsonrpc/ftpdjsonrpc.py -n 500 ftpd-500.dat
	date
	@echo ''
	@echo 'Performace Testing for 600 FTP Evenet'
	date
	python ../ftpdjsonrpc/ftpdjsonrpc.py -n 600 ftpd-600.dat
	date
	@echo ''
	@echo 'Performace Testing for 700 FTP Evenet'
	date
	python ../ftpdjsonrpc/ftpdjsonrpc.py -n 700 ftpd-700.dat
	date
	@echo ''
	@echo 'Performace Testing for 800 FTP Evenet'
	date
	python ../ftpdjsonrpc/ftpdjsonrpc.py -n 800 ftpd-800.dat
	date
	@echo ''
	@echo 'Performace Testing for 900 FTP Evenet'
	date
	python ../ftpdjsonrpc/ftpdjsonrpc.py -n 900 ftpd-900.dat
	date
	@echo ''
	@echo 'Performace Testing for 1000 FTP Evenet'
	date
	python ../ftpdjsonrpc/ftpdjsonrpc.py -n 1000 ftpd-1000.dat
	date

vsftpd:
	@echo off
	cls
	@echo 'Performace Testing for 100 VSFTPD Evenet'
	date
	python ../vsftpdjsonrpc/vsftpdjsonrpc.py -n 100 vsftpd-100.dat
	date
	@echo ''
	@echo 'Performace Testing for 200 VSFTPD Evenet'
	date
	python ../vsftpdjsonrpc/vsftpdjsonrpc.py -n 200 vsftpd-200.dat
	date
	@echo ''
	@echo 'Performace Testing for 300 VSFTPD Evenet'
	date
	python ../vsftpdjsonrpc/vsftpdjsonrpc.py -n 300 vsftpd-300.dat
	date
	@echo ''
	@echo 'Performace Testing for 400 VSFTPD Evenet'
	date
	python ../vsftpdjsonrpc/vsftpdjsonrpc.py -n 400 vsftpd-400.dat
	date
	@echo ''
	@echo 'Performace Testing for 500 VSFTPD Evenet'
	date
	python ../vsftpdjsonrpc/vsftpdjsonrpc.py -n 500 vsftpd-500.dat
	date
	@echo ''
	@echo 'Performace Testing for 600 VSFTPD Evenet'
	date
	python ../vsftpdjsonrpc/vsftpdjsonrpc.py -n 600 vsftpd-600.dat
	date
	@echo ''
	@echo 'Performace Testing for 700 VSFTPD Evenet'
	date
	python ../vsftpdjsonrpc/vsftpdjsonrpc.py -n 700 vsftpd-700.dat
	date
	@echo ''
	@echo 'Performace Testing for 800 VSFTPD Evenet'
	date
	python ../vsftpdjsonrpc/vsftpdjsonrpc.py -n 800 vsftpd-800.dat
	date
	@echo ''
	@echo 'Performace Testing for 900 VSFTPD Evenet'
	date
	python ../vsftpdjsonrpc/vsftpdjsonrpc.py -n 900 vsftpd-900.dat
	date
	@echo ''
	@echo 'Performace Testing for 1000 VSFTPD Evenet'
	date
	python ../vsftpdjsonrpc/vsftpdjsonrpc.py -n 1000 vsftpd-1000.dat
	date

ncsa:
	@echo off
	cls
	@echo 'Performace Testing for 100 NCSA Evenet'
	date
	python ../ncsajsonrpc/ncsajsonrpc.py -n 100 ncsa-100.dat
	date
	@echo ''
	@echo 'Performace Testing for 200 NCSA Evenet'
	date
	python ../ncsajsonrpc/ncsajsonrpc.py -n 200 ncsa-200.dat
	date
	@echo ''
	@echo 'Performace Testing for 300 NCSA Evenet'
	date
	python ../ncsajsonrpc/ncsajsonrpc.py -n 300 ncsa-300.dat
	date
	@echo ''
	@echo 'Performace Testing for 400 NCSA Evenet'
	date
	python ../ncsajsonrpc/ncsajsonrpc.py -n 400 ncsa-400.dat
	date
	@echo ''
	@echo 'Performace Testing for 500 NCSA Evenet'
	date
	python ../ncsajsonrpc/ncsajsonrpc.py -n 500 ncsa-500.dat
	date
	@echo ''
	@echo 'Performace Testing for 600 NCSA Evenet'
	date
	python ../ncsajsonrpc/ncsajsonrpc.py -n 600 ncsa-600.dat
	date
	@echo ''
	@echo 'Performace Testing for 700 NCSA Evenet'
	date
	python ../ncsajsonrpc/ncsajsonrpc.py -n 700 ncsa-700.dat
	date
	@echo ''
	@echo 'Performace Testing for 800 NCSA Evenet'
	date
	python ../ncsajsonrpc/ncsajsonrpc.py -n 800 ncsa-800.dat
	date
	@echo ''
	@echo 'Performace Testing for 900 NCSA Evenet'
	date
	python ../ncsajsonrpc/ncsajsonrpc.py -n 900 ncsa-900.dat
	date
	@echo ''
	@echo 'Performace Testing for 1000 NCSA Evenet'
	date
	python ../ncsajsonrpc/ncsajsonrpc.py -n 1000 ncsa-1000.dat
	date