all:
	cls ; python netflowjsonrpc.py ../data/netflow01.xml
test:
	cls ; python netflowjsonrpc.py ../data/netflow01.xml ../data/netflow02.xml ../data/netflow03.xml
data:
	cls ; more ../data/netflow01.xml
