all:
	make clean
	make sim1
	make sim2
	make simulation
	make log1
	make log2
	make log3
	make log4

demo:
	make clean
	cls ; python simulation.py demo.xml
	
sim1:
	make clean
	cls ; python simulation.py sim01.xml

sim2:
	make clean
	cls ; python simulation.py sim02.xml

simulation:
	make clean
	cls ; python simulation.py log00.xml

clean:
	cls ; rm -rf core *.pyc *.bak simulation/*

log1:
	make clean
	cls ; python simulation.py log01.xml

log2:
	make clean
	cls ; python simulation.py log02.xml

log3:
	make clean
	cls ; python simulation.py log03.xml

log4:
	make clean
	cls ; python simulation.py log04.xml
